services:

  app:

    build: .

    container_name: app

    expose:
      - "3000"

    volumes:
      - .:/app
      - /app/node_modules

    command: node server.js

    depends_on:
      - redis

  redis:

    image: redis:latest

    container_name: redis

  nginx:

    image: nginx:latest

    container_name: nginx

    ports:
      - "443:443"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./cert:/etc/nginx/cert:ro

    depends_on:
      - app